config/routes.rb
Rails.application.routes.draw do
  root to: 'shifts#index'
  resources :shifts, only: [ :index, :new, :create, :show ]
  resources :workers, only: [ :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :worker
  validates :planning_id, presence: true
  validates :worker_id, presence: true
  validates :start_date, presence: true
end

app/models/worker.rb
class Worker < ApplicationRecord
    has_many :shift
     validates :first_name, presence: true
     validates :price_per_shift, presence: true
     validates :category, presence: true, inclusion: { in: %w(medic interne interim),
    message: "%{value} is not a valid category" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
    def index
     
      @shifts = Shift.all
      @workers = Worker.all
    end
    def show

    @shift = Shift.find(params[:id])
    @worker = Worker.find_by_id(@shift.worker_id)
    end

  def new
    @shift = Shift.new
     @workers = Worker.all
  end
  def create
@shift = Shift.new(shift_params)
   if @shift.save
    redirect_to root_path
   else
     render :new
   end
  end


  private

  def shift_params
    params.require(:shift).permit(:planning_id, :worker_id, :start_date)
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
    
    def new
    @worker = Worker.new
    end
  def create
@worker = Worker.new(worker_params)
   if @worker.save
    redirect_to root_path
   else
     render :new
   end
  end

  def edit
    @worker = Worker.find(params[:id])

  end
  def update
    @worker = Worker.find(params[:id])
    if @worker.update(worker_params)
      redirect_to root_path
    else
      render :edit
    end
  end



  private

  def worker_params
    params.require(:worker).permit(:first_name, :price_per_shift, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Shifter</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
   <h13> Shifter </h13>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">



    <!-- Text link -->

      <%= link_to "All Shift", shifts_path, class: "navbar-wagon-item navbar-wagon-link" %>



    <!-- Button (call-to-action) -->

    <%= link_to "ADD Shift", new_shift_path, class:"navbar-wagon-item navbar-wagon-button btn"  %>
    <%= link_to "ADD worker", new_worker_path, class:"navbar-wagon-item navbar-wagon-button btn"  %>






 
</div>

</div>

app/views/shifts/_form.html.erb
  <div class="wrapper">
    <div class=" container form-signin">
<%= simple_form_for @shift do |f| %>

      <%= f.input :planning_id, label: "planning_id" %>
      <%= f.input :worker_id, :collection => @workers,:label_method => :first_name, :value_method => :id,:label => "workers" ,:include_blank => false, prompt:"choose the worker" %>
      <%= f.input :start_date, label: "date" %>
      <%= f.button :submit, "ADD", class: "btn btn-primary btn-lg btn-block btn-color" %>
<% end %>
</div>
</div>

app/views/shifts/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-9 col-sm-9 col-sm-offset-1">
            <h1 class="text-center"> All Shifts </h1>
            <% @shifts.each do |shift| %>
                <div class="product">
                    <div class='product-body'>
                        <h3 class="ttext">Worker : <%= @workers.find_by_id(shift.worker_id).first_name %> (id:<%= shift.worker_id %>)</h3>
                        <p class="ttext">Start date :<%= shift.start_date %></p>
                    </div>
                    <ul class="list-inline product-controls">
                        <li>
                            <%= link_to shift_path(shift) do %>
                                <i class="fa fa-eye"></i>
                            <% end %>
                        </li>
                        <li>
                            <%= link_to edit_worker_path(shift.worker_id) do %>
                                <i class="fa fa-pencil"></i>
                            <% end %>
                        </li>
                     </ul>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/shifts/new.html.erb
<%=  render "form" %>

app/views/shifts/show.html.erb
<div class="container">
    <h1>SHIFT INFORMATIONS</h1>
    <div class="container">
        <p>worker_id :<%= @shift.worker_id %><br>
        worker name: <%= @worker.first_name %><br>
        planning_id:<%= @shift.planning_id %><br>
        start_date: <%= @shift.start_date.strftime('%A %d %B %Y') %><br>
        price : <% if @shift.start_date.strftime('%A') == "Saturday" || @shift.start_date.strftime('%A') == "Sunday" %>
            <%=  price = @worker.price_per_shift * 2%><br>
        <% else %>
            <%= price = @worker.price_per_shift %><br>
        <% end %>
            Commission : <% if @worker.status == "interim" %>
            <%= price.to_f * 0.05 + 80.0%><br>
        <% else %>
            <%= price.to_f * 0.05 %><br>
        <% end %>
    </div></p>
</div>

app/views/workers/_form.html.erb
  <div class="wrapper">
    <div class=" container form-signin">
<%= simple_form_for @worker do |f| %>
      <%= f.input :first_name, label: "first_name" %>
      <%= f.input :price_per_shift, label: "price_per_shift" %>
     <%= f.input :status, collection: ["medic", "interne", "interim"], prompt:"Status", label: "Status"  %>
      <%= f.button :submit, "ADD", class: "btn btn-primary btn-lg btn-block btn-color" %>
<% end %>
</div>
</div>

app/views/workers/edit.html.erb
<%=  render "form" %>

app/views/workers/new.html.erb
<%=  render "form" %>